homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 365
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York

  customize: !include_dir_merge_named customizations

zone:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  radius: 250

sensor: !include_dir_merge_list sensors
group: !include_dir_merge_named groups
automation: !include_dir_list automations
device_tracker: !include_dir_merge_list device_tracker

# Show links to resources in log and frontend
# introduction:

# Alarm
alarm_control_panel:
  platform: manual
  pending_time: 5


# Enables the frontend
frontend:

http:
  api_password: !secret api_password
  server_port: !secret server_port
  ssl_certificate: '/etc/letsencrypt/live/home.cynicated.com/fullchain.pem'
  ssl_key: '/etc/letsencrypt/live/home.cynicated.com/privkey.pem'

zwave:
  usb_path: /dev/ttyACM0
  config_path: /srv/hass/hass_venv/lib/python3.4/site-packages/libopenzwave-0.3.1-py3.4-linux-armv7l.egg/config

notify:
  - name: twilio_sms
    platform: twilio_sms
    account_sid: !secret twilio_sid
    auth_token: !secret twilio_auth
    from_number: !secret twilio_from

mqtt:
  broker: localhost
  username: !secret mqtt_user
  password: !secret mqtt_pass


switch:

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
# conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:
  exclude:
    entities:
      - sensor.cpu_use
      - sensor.disk_use_
      - sensor.disk_use_varlog
      - sensor.ram_use
      - sensor.ram_free
      - sensor.swap_use
      - sensor.swap_free
      - sensor.last_boot
      - sensor.since_last_boot
      - sensor.received_wlan0
      - sensor.sent_wlan0
      - sensor.packets_received_wlan0
      - sensor.packets_sent_wlan0

recorder:
  purge_days: 7
# Track the sun
sun:

# Weather Prediction
#sensor:
#  platform: yr
