alias: "KW Leave Notify"
initial_state: false
trigger:
  - platform: state
    entity_id: device_tracker.kwood_iphone
    from: 'home'
    to: 'not_home'
action:
  service: notify.twilio_sms
  data:
    message: 'KW Left Home'
    target:
      - !secret mw_sms
