alias: "MW Arrive Home"
trigger:
  - platform: state
    entity_id: device_tracker.mwood_nexus6p
    to: 'home'
    from: 'not_home'
condition:
  - condition: sun
    after: sunset
    after_offset: "-00:30:00"
action:
  - service: notify.twilio_sms
    data:
      message: 'MW arrived at home!'
      target:
        - !secret mw_sms
  - service: switch.turn_on
    entity_id: switch.light01_switch_3_0
