alias: "MW Arrive Work"
initial_state: false
trigger:
  - platform: state
    entity_id: device_tracker.mwood_nexus6p
    to: 'MW_Work'
    for:
      minutes: 5
action:
  service: notify.twilio_sms
  data:
    message: 'MW arrived at work!'
    target:
      - !secret mw_sms
