alias: "MW Left Work"
initial_state: false
trigger:
  - platform: state
    entity_id: device_tracker.mwood_nexus6p
    to: 'not_home'
    from: 'MW_Work'
    for:
      minutes: 5
action:
  service: notify.twilio_sms
  data:
    message: 'MW left work!'
    target:
      - !secret mw_sms
